In [1]:
import torch

In [4]:
torch.cuda.is_available()

True

In [7]:
torch.cuda.init()

In [10]:
torch.cuda.current_device()

0

In [12]:
torch.cuda.device_count()

1

In [24]:
print(torch.cuda.memory_allocated())
print(torch.cuda.memory_cached())

512
2097152


In [16]:
cuda = torch.device('cuda')
cuda

device(type='cuda')

In [22]:
cuda_0 = torch.device('cuda:0')
cuda_1 = torch.device('cuda:1') 

cuda_0, cuda_1

(device(type='cuda', index=0), device(type='cuda', index=1))

In [21]:
x = torch.tensor([10., 20.])
x

tensor([10., 20.])

In [23]:
x_cuda = torch.tensor([10., 20.], device = cuda_0)
x_cuda

tensor([10., 20.], device='cuda:0')

In [25]:
x2_cuda = torch.tensor([10., 20.], device = cuda_1)
x2_cuda

RuntimeError: CUDA error: invalid device ordinal


### Returning a copy of that object in the cuda memory

In [31]:
# transfering a tensor from CPU to GPU memory
y = x.cuda()
y

tensor([10., 20.], device='cuda:0')

In [38]:
# this way I can use a specifc cuda device
with torch.cuda.device(0):
    print("Inside of the cuda:0 context :"  + str(torch.cuda.current_device()))

Inside of the cuda:0 context :0


In [42]:
# this way we could have made a copy on the other device
# b1 = y.to(device="cuda:1")
# b1

In [72]:
a = torch.tensor([10., 20.])
a1 = torch.tensor([10., 20.], device = 'cuda:0')

In [73]:
# b1 = torch.tensor(a1, device='cuda:0')
b1 = a1.clone()

b1

tensor([10., 20.], device='cuda:0')

In [74]:
a1[0] = 50
b1

tensor([10., 20.], device='cuda:0')

In [45]:
# 2 different types of data that can't added up
# also both tensors have to be placed on the same GPU device
sum_a = a + a1
sum_a

RuntimeError: expected backend CPU and dtype Float but got backend CUDA and dtype Float

In [46]:
sum_a = y + a1
sum_a

tensor([20., 40.], device='cuda:0')

In [50]:
torch.cuda.empty_cache()
torch.cuda.memory_cached()

2097152

### Opearting with new_ operators

In [51]:
# the new_ operators have the capability to preserve the context of the original tensor
preserve_context = x.new_full([2, 2], fill_value = 1.1)
preserve_context

tensor([[1.1000, 1.1000],
        [1.1000, 1.1000]])

In [54]:
preserve_context_0 = y.new_full([2,2], fill_value = 1.1)
preserve_context_0

tensor([[1.1000, 1.1000],
        [1.1000, 1.1000]], device='cuda:0')